#!/bin/bash

# 0xAARRGGBB
options=(
	style=round
	width=9.0
	hidpi=on
	active_color=0xaa34b334
	inactive_color=0xaaed872d
	# idk if i'm on master?
	# if i see red, it's from here
	# background_color=0xaaff0000
)
#?
borders "${options[@]}"
