#!/bin/bash


source "$HOME/.config/sketchybar/colors.sh"
PLUGIN_DIR="$CONFIG_DIR/plugins"
ITEM_DIR="$HOME/.config/sketchybar/items" # Directory where the items are configured
ITEM_CORNER_RADIUS=3
ITEM_BACKGROUND_HEIGHT=26
ITEM_PADDING=14

sketchybar --bar position=top height=40 blur_radius=30 color=0x40000000

default=(
  icon.color=$ICON_COLOR
  label.color=$LABEL_COLOR
	# background.color=$GREY
	background.corner_radius=5            
	background.height=24
  padding_left=5
  padding_right=5
  icon.font="Hack Nerd Font:Bold:17.0"
  label.font="Hack Nerd Font:Bold:14.0"
  icon.padding_left=4
  icon.padding_right=10
  label.padding_left=4
  label.padding_right=10
)
sketchybar --default "${default[@]}"

sketchybar --add item time right \
	--set time update_freq=1 \
	script="$PLUGIN_DIR/time.sh" \
	icon.padding_right=0 \
	icon.padding_left=0 \
	background.padding_left=0 \
	background.padding_right=0 

sketchybar --add item date right \
	--set date update_freq=120 \
	script="$PLUGIN_DIR/date.sh" \
	icon.padding_right=0 \
	icon.padding_left=0 \
	background.padding_left=0 \
	background.padding_right=0 

source "$HOME/.config/sketchybar/colors.sh" # Loads all defined colors 
source "$HOME/.config/sketchybar/icons.sh" # Loads all defined icons
# source "$ITEM_DIR/right/wifi.sh"
# source "$ITEM_DIR/right/cpu_temp.sh"
# source "$ITEM_DIR/right/weather.sh"

source "$ITEM_DIR/spotify.sh"

source "$ITEM_DIR/left/spaces.sh"
source "$ITEM_DIR/left/front_app.sh"
source "$ITEM_DIR/left/yabai_mode2.sh"

sketchybar --add item volume right \
           --set volume script="$PLUGIN_DIR/volume.sh" \
           --subscribe volume volume_change 

sketchybar --add item battery right \
           --set battery update_freq=120 script="$PLUGIN_DIR/battery.sh" \
           --subscribe battery system_woke power_source_change

sketchybar --hotload true

sketchybar --update

echo "sketchybar configuration loaded.."
