[general]
import = [
	# "~/.config/alacritty/themes/catppuccin-frappe.toml",
	# "~/.config/alacritty/themes/catppuccin-frappe.toml",
	"~/.config/alacritty/themes/catppuccin-macchiato.toml",
	# "~/.config/alacritty/themes/catppuccin-mocha.toml",
	# "~/.config/alacritty/themes/catppuccin-latte.toml",
]

[env]
TERM = "xterm-256color"
# [colors.primary]
# background = '0xFFFFFF'
# foreground = '0x000000'
[scrolling]
# Maximum number of lines in the scrollback buffer.
# Specifying '0' will disable scrolling.
history = 10000
# Scrolling distance multiplier.
multiplier = 3

[font]
size = 14

[font.glyph_offset]
y = 1

[font.normal]
family = "MesloLGL Nerd Font"
# family = "JetBrainsMonoNL Nerd Font Mono"

[mouse]
hide_when_typing = false

[selection]
save_to_clipboard = true

[terminal.shell]
args = ["-l", "-c", "tmux new-session -A -s default"]
program = "/bin/zsh"

[window]
decorations = "Buttonless"
opacity = 0.8
blur = true
padding.x = 10
padding.y = 10


# Define a hint for URLs (including vscode://).
[[hints.enabled]]
# On macOS
command = "open"
hyperlinks = true
post_processing = true
persist = false
mouse.enabled = true
binding = { key = "O", mods = "Control|Shift" }
regex = "(ipfs:|ipns:|magnet:|mailto:|gemini://|gopher://|https://|http://|news:|file:|git://|ssh:|ftp://|vscode://)[^\u0000-\u001F\u007F-\u009F<>\"\\s{-}\\^⟨⟩`\\\\]+"
