[general]
import = [
	# "~/dotfiles/.config/alacritty/themes/catppuccin-frappe.toml",
	# "~/.config/alacritty/themes/catppuccin-frappe.toml",
	"~/.config/alacritty/themes/catppuccin-macchiato.toml",
	# "~/.config/alacritty/themes/catppuccin-mocha.toml",
]

[env]
TERM = "xterm-256color"

[scrolling]
# Maximum number of lines in the scrollback buffer.
# Specifying '0' will disable scrolling.
history = 10000
# Scrolling distance multiplier.
multiplier = 3

[font]
size = 14

[font.glyph_offset]
y = 1

[font.normal]
family = "MesloLGL Nerd Font"
# family = "JetBrainsMonoNL Nerd Font Mono"

[mouse]
hide_when_typing = false

[selection]
save_to_clipboard = true

[terminal.shell]
# args = ["-l", "-c", "tmux"]
# When opening a new alacritty it connects to any existing
# tmux instance... sometimes I don't want that...
args = [
	"--login",
	"-c",
	"/opt/homebrew/bin/tmux attach || //opt/homebrew/bin/tmux",
]
program = "/bin/zsh"

[window]
decorations = "buttonless"
opacity = 1.0

[window.padding]
x = 10
y = 10


# Define a hint for URLs (including vscode://).
[[hints.enabled]]
# On macOS
command = "open"
hyperlinks = true
post_processing = true
persist = false
mouse.enabled = true
binding = { key = "O", mods = "Control|Shift" }
regex = "(ipfs:|ipns:|magnet:|mailto:|gemini://|gopher://|https://|http://|news:|file:|git://|ssh:|ftp://|vscode://)[^\u0000-\u001F\u007F-\u009F<>\"\\s{-}\\^⟨⟩`\\\\]+"

# # wip
# [colors.cursor]
# cursor = "CellForeground"
# text = "CellBackground"

# [colors.primary]
# background = "#1d1f21"
# foreground = "#c5c8c6"

# [colors.vi_mode_cursor]
# cursor = "CellForeground"
# text = "CellBackground"
